trigger:
- master

pr:
- master

jobs:
- job: 'ubuntu16'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    LLVM_CLANG: 'clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04'
  steps:
  - script: ci/setup_clang_posix
    displayName: 'Install LLVM and clang'
  - script: ci/setup_nim_linux_x64
    displayName: 'Install Nim'
  - script: ci/run_tests_posix
    displayName: 'Run tests'
- job: 'ubuntu18'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    LLVM_CLANG: 'clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04'
  steps:
  - script: ci/setup_clang_posix
    displayName: 'Install LLVM and clang'
  - script: ci/setup_nim_linux_x64
    displayName: 'Install Nim'
  - script: ci/run_tests_posix
    displayName: 'Run tests'
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  variables:
    LLVM_CLANG: 'clang+llvm-9.0.0-x86_64-darwin-apple'
  steps:
  - script: ci/setup_clang_posix
    displayName: 'Install LLVM and clang'
  - script: ci/setup_nim_osx
    displayName: 'Install Nim'
  - script: ci/run_tests_posix
    displayName: 'Run tests'
